import { Repuesto, HighRotationItem, LowRotationItem, MarketOpportunity, DiscontinueAlert, SuggestedPurchaseItem } from '../types/inventory';

export const INITIAL_REPUESTOS: Repuesto[] = [
  {
    id: 1,
    sku: 'FLT-TVS-125',
    nombre: 'Filtro de Aire TVS Raider 125',
    descripcion: 'Filtro de papel plisado alta captación',
    categoria: 'Aceites y Lubricantes',
    proveedor: 'Repuestos Originales del Valle',
    modelos_compatibles: 'TVS Raider 125cc',
    ubicacion: 'Estante A-2',
    precio_costo: 16000,
    precio_venta: 28000,
    stock_actual: 14,
    stock_minimo: 6,
    stock_seguridad: 2,
    clasificacion_abc: 'A',
    dias_sin_movimiento: 3,
    demanda_estimada: 18,
    estado: 'EN_STOCK',
    ventas_ultimos_30d: 22
  },
  {
    id: 2,
    sku: 'FRN-YM-012',
    nombre: 'Pastillas de Freno Delanteras Yamaha FZ / R15',
    descripcion: 'Pastillas sinterizadas cerámicas de alta fricción',
    categoria: 'Sistema de Frenos',
    proveedor: 'Repuestos Andina',
    modelos_compatibles: 'Yamaha FZ 2.0 / R15 V3',
    ubicacion: 'Cajón F-01',
    precio_costo: 28000,
    precio_venta: 42000,
    stock_actual: 0,
    stock_minimo: 8,
    stock_seguridad: 3,
    clasificacion_abc: 'A',
    dias_sin_movimiento: 0,
    demanda_estimada: 20,
    estado: 'AGOTADO',
    ventas_ultimos_30d: 35
  },
  {
    id: 3,
    sku: 'LUB-MO-710',
    nombre: 'Aceite Motul 7100 4T 10W40 1L',
    descripcion: 'Sintético 100% Ester tecnología motos deportivas',
    categoria: 'Aceites y Lubricantes',
    proveedor: 'LubriMotos S.A.',
    modelos_compatibles: 'Yamaha, Honda, KTM, Pulsar',
    ubicacion: 'Bodega L-12',
    precio_costo: 48000,
    precio_venta: 68000,
    stock_actual: 2,
    stock_minimo: 12,
    stock_seguridad: 4,
    clasificacion_abc: 'A',
    dias_sin_movimiento: 1,
    demanda_estimada: 28,
    estado: 'BAJO_STOCK',
    ventas_ultimos_30d: 42
  },
  {
    id: 4,
    sku: 'TRM-BJ-428',
    nombre: 'Kit de Arrastre 428H Pulsar 200NS',
    descripcion: 'Piñón + Corona + Cadena O-Ring reforzada',
    categoria: 'Transmisión y Arrastre',
    proveedor: 'MotoPartes del Centro',
    modelos_compatibles: 'Bajaj Pulsar NS200 / AS200',
    ubicacion: 'Estante C-04',
    precio_costo: 110000,
    precio_venta: 145000,
    stock_actual: 3,
    stock_minimo: 4,
    stock_seguridad: 1,
    clasificacion_abc: 'B',
    dias_sin_movimiento: 4,
    demanda_estimada: 8,
    estado: 'BAJO_STOCK',
    ventas_ultimos_30d: 12
  },
  {
    id: 5,
    sku: 'ELE-NG-8EA',
    nombre: 'Bujía NGK CPR8EA-9',
    descripcion: 'Ajuste universal estándar de encendido rápido',
    categoria: 'Sistema Eléctrico',
    proveedor: 'Importaciones Japón',
    modelos_compatibles: 'Universal Yamaha / Honda / Hero',
    ubicacion: 'Cajón E-02',
    precio_costo: 14000,
    precio_venta: 24000,
    stock_actual: 3,
    stock_minimo: 10,
    stock_seguridad: 3,
    clasificacion_abc: 'A',
    dias_sin_movimiento: 2,
    demanda_estimada: 30,
    estado: 'BAJO_STOCK',
    ventas_ultimos_30d: 38
  },
  {
    id: 6,
    sku: 'FRN-HD-004',
    nombre: 'Banda de Freno Trasera Honda CB125F',
    descripcion: 'Zapatas mecánicas libres de asbesto',
    categoria: 'Sistema de Frenos',
    proveedor: 'Frenos y Partes de Colombia',
    modelos_compatibles: 'Honda CB125F / CB110',
    ubicacion: 'Estante B-03',
    precio_costo: 18000,
    precio_venta: 32000,
    stock_actual: 22,
    stock_minimo: 5,
    stock_seguridad: 2,
    clasificacion_abc: 'B',
    dias_sin_movimiento: 8,
    demanda_estimada: 10,
    estado: 'EN_STOCK',
    ventas_ultimos_30d: 15
  },
  {
    id: 7,
    sku: 'GUA-UNV-01',
    nombre: 'Cable de Embrague Universal Reforzado',
    descripcion: 'Acero trenzado con forro antifricción',
    categoria: 'Embrague',
    proveedor: 'Repuestos Originales del Valle',
    modelos_compatibles: 'Yamaha, Suzuki, AKT 125, Pulsar',
    ubicacion: 'Gaveta D-08',
    precio_costo: 9500,
    precio_venta: 18000,
    stock_actual: 35,
    stock_minimo: 10,
    stock_seguridad: 3,
    clasificacion_abc: 'A',
    dias_sin_movimiento: 1,
    demanda_estimada: 48,
    estado: 'EN_STOCK',
    ventas_ultimos_30d: 48
  },
  {
    id: 8,
    sku: 'EMB-KYM-125',
    nombre: 'Corona de Embrague Kymco Agility',
    descripcion: 'Campana clutch scooter 125cc',
    categoria: 'Embrague',
    proveedor: 'Repuestos Originales del Valle',
    modelos_compatibles: 'Agility RS / Digital 125',
    ubicacion: 'Estante D-01',
    precio_costo: 125000,
    precio_venta: 180000,
    stock_actual: 1,
    stock_minimo: 1,
    stock_seguridad: 0,
    clasificacion_abc: 'C',
    dias_sin_movimiento: 95,
    demanda_estimada: 1,
    estado: 'EN_STOCK',
    ventas_ultimos_30d: 1
  },
  {
    id: 9,
    sku: 'ILU-SZ-250',
    nombre: 'Faro Delantero Completo Suzuki Gixxer 250',
    descripcion: 'Óptica LED completa original carenada',
    categoria: 'Iluminación',
    proveedor: 'Repuestos Originales del Valle',
    modelos_compatibles: 'Suzuki Gixxer 250 SF',
    ubicacion: 'Vitrina Segura 2',
    precio_costo: 420000,
    precio_venta: 580000,
    stock_actual: 1,
    stock_minimo: 1,
    stock_seguridad: 0,
    clasificacion_abc: 'C',
    dias_sin_movimiento: 180,
    demanda_estimada: 0,
    estado: 'EN_STOCK',
    ventas_ultimos_30d: 0
  },
  {
    id: 10,
    sku: 'SUS-YM-025',
    nombre: 'Amortiguador Trasero Monoshock FZ25',
    descripcion: 'Nitrógeno regulable Yamaha original',
    categoria: 'Suspensión',
    proveedor: 'Repuestos Andina',
    modelos_compatibles: 'Yamaha FZ 25',
    ubicacion: 'Estante S-05',
    precio_costo: 310000,
    precio_venta: 440000,
    stock_actual: 1,
    stock_minimo: 1,
    stock_seguridad: 0,
    clasificacion_abc: 'C',
    dias_sin_movimiento: 120,
    demanda_estimada: 0,
    estado: 'EN_STOCK',
    ventas_ultimos_30d: 0
  },
  {
    id: 11,
    sku: 'FRN-AX4-BND',
    nombre: 'Bandas de Freno Traseras AX4',
    descripcion: 'Zapatas de frenos para modelos 100cc',
    categoria: 'Sistema de Frenos',
    proveedor: 'Frenos y Partes de Colombia',
    modelos_compatibles: 'Suzuki AX4 100cc',
    ubicacion: 'Estante 3B',
    precio_costo: 15000,
    precio_venta: 28000,
    stock_actual: 6,
    stock_minimo: 2,
    stock_seguridad: 0,
    clasificacion_abc: 'C',
    dias_sin_movimiento: 75,
    demanda_estimada: 0,
    estado: 'EN_STOCK',
    ventas_ultimos_30d: 0
  },
  {
    id: 12,
    sku: 'ESP-VINT-CR',
    nombre: 'Espejos Universales Tipo Vintage (Cromados)',
    descripcion: 'Juego de espejos retrovisores cromados redondos',
    categoria: 'Accesorios',
    proveedor: 'Importaciones Japón',
    modelos_compatibles: 'Custom / Cafe Racer',
    ubicacion: 'Vitrina 1',
    precio_costo: 35000,
    precio_venta: 65000,
    stock_actual: 1,
    stock_minimo: 1,
    stock_seguridad: 0,
    clasificacion_abc: 'C',
    dias_sin_movimiento: 90,
    demanda_estimada: 0,
    estado: 'EN_STOCK',
    ventas_ultimos_30d: 0
  }
];

export const TOP_MAYOR_ROTACION: HighRotationItem[] = [
  { id: 1, nombre: 'Aceite Semi-sintético Yamalube 4T', unidades: 84, objetivo_rotacion_pct: 95, etiqueta: 'Alta demanda' },
  { id: 2, nombre: 'Filtro de Aceite Genérico Honda/Yamaha', unidades: 62, objetivo_rotacion_pct: 80, etiqueta: 'Frecuencia constante' },
  { id: 3, nombre: 'Guaya / Cable de Embrague Universal', unidades: 48, objetivo_rotacion_pct: 65, etiqueta: 'Reemplazo habitual' },
  { id: 4, nombre: 'Pastillas de Freno Traseras Pulsar', unidades: 41, objetivo_rotacion_pct: 55, etiqueta: 'Servicio de frenos' },
  { id: 5, nombre: 'Cámara / Neumático Rin 17 (2.75–17)', unidades: 37, objetivo_rotacion_pct: 48, etiqueta: 'Rotación estable' }
];

export const TOP_MENOR_ROTACION: LowRotationItem[] = [
  { id: 1, nombre: 'Faro Delantero Completo Suzuki Gixxer 250', dias: 180, capital_inmovilizado_cop: 420000, capital_usd: 145.0, sugerencia: 'Devolución o promo' },
  { id: 2, nombre: 'CDI Racing Universal 12V', dias: 145, capital_inmovilizado_cop: 180000, capital_usd: 60.0, sugerencia: 'Baja compatibilidad local' },
  { id: 3, nombre: 'Amortiguador Trasero Monoshock FZ25', dias: 120, capital_inmovilizado_cop: 310000, capital_usd: 110.0, sugerencia: 'Alto costo unitario' },
  { id: 4, nombre: 'Llanta Pistera 140/70–17 Michelin Pilot', dias: 110, capital_inmovilizado_cop: 270000, capital_usd: 95.0, sugerencia: 'Ofrecer en paquete de cambio' },
  { id: 5, nombre: 'Corona de Embrague Kymco Agility', dias: 95, capital_inmovilizado_cop: 125000, capital_usd: 45.0, sugerencia: 'Lote sobrante anterior' }
];

export const INITIAL_SUGGESTED_PURCHASES: SuggestedPurchaseItem[] = [
  {
    id: 1,
    sku: '10W40-MSM',
    nombre: 'Aceite Semisintético 4T 10W-40',
    detalle: 'Mobil Super Moto • Garrafa 1L • Ref: 10W40-MSM',
    clasificacion: 'Clase A - Alta',
    stock_actual: 2,
    stock_minimo: 8,
    cantidad_sugerida: 18,
    unidad: 'unidades',
    proveedor: 'Distribuidora MotoLube SAS',
    tiempo_entrega: 'Entrega: 24h',
    costo_unitario: 26666,
    costo_total: 480000,
    aprobado: true
  },
  {
    id: 2,
    sku: 'FRN-YM-CER',
    nombre: 'Pastillas de Freno Delanteras Cerámicas',
    detalle: 'Yamaha FZ 16 / Pulsar NS200 • Ichimax Racing',
    clasificacion: 'Clase A - Alta',
    stock_actual: 1,
    stock_minimo: 6,
    cantidad_sugerida: 12,
    unidad: 'juegos',
    proveedor: 'Frenos y Partes de Colombia',
    tiempo_entrega: 'Entrega: 48h',
    costo_unitario: 30000,
    costo_total: 360000,
    aprobado: true
  },
  {
    id: 3,
    sku: 'TRM-BJ-428',
    nombre: 'Kit de Arrastre Reforzado 428H',
    detalle: 'KMC / Piñón y Corona Acero 1045 • Universal 125–150cc',
    clasificacion: 'Clase B - Media',
    stock_actual: 0,
    stock_minimo: 4,
    cantidad_sugerida: 5,
    unidad: 'kits',
    proveedor: 'Importadora de Cadenas Andina',
    tiempo_entrega: 'Entrega: Inmediata',
    costo_unitario: 110000,
    costo_total: 550000,
    aprobado: true
  },
  {
    id: 4,
    sku: 'FLT-OEM-16510',
    nombre: 'Filtro de Aceite Original Sellado',
    detalle: 'Suzuki Gixxer 150 / 250 / GSX • OEM 16510–05240',
    clasificacion: 'Clase A - Alta',
    stock_actual: 3,
    stock_minimo: 10,
    cantidad_sugerida: 15,
    unidad: 'unidades',
    proveedor: 'Repuestos Originales del Valle',
    tiempo_entrega: 'Entrega: 24h',
    costo_unitario: 12000,
    costo_total: 180000,
    aprobado: true
  }
];

export const INITIAL_OPPORTUNITIES: MarketOpportunity[] = [
  {
    id: 1,
    nombre: 'Líquido de Frenos DOT 4 Racing (250ml)',
    demanda_tendencia: '+38% demanda',
    justificacion: 'Alta solicitud en los últimos 28 mantenimientos de frenos. Proyección de margen de ganancia neta del 45% frente al fluido convencional.',
    costo_pack_inicial: 95000,
    unidades_pack: 6,
    categoria: 'Sistema de Frenos',
    agregado: false
  },
  {
    id: 2,
    nombre: 'Bombillos LED H4 Alta Potencia (Canbus)',
    demanda_tendencia: 'Tendencia urbana',
    justificacion: '7 de cada 10 motociclistas urbanos consultan por actualización de farola delantera. Rotación estimada en 14 días.',
    costo_pack_inicial: 140000,
    unidades_pack: 6,
    categoria: 'Iluminación y Carenajes',
    agregado: false
  }
];

export const INITIAL_DISCONTINUE_ALERTS: DiscontinueAlert[] = [
  {
    repuesto_id: 11,
    sku: 'FRN-AX4-BND',
    nombre: 'Bandas de Freno Traseras AX4',
    clasificacion_abc: 'C',
    stock_inmovilizado: 6,
    ubicacion: 'estante 3B',
    capital_congelado_cop: 90000,
    dias_sin_movimiento: 75,
    motivo: '0 salidas / 75 días. Modelo desfasado en parque automotor activo.',
    sugerencia_accion: 'No reordenar hasta liquidar existencias',
    pausado: false
  },
  {
    repuesto_id: 12,
    sku: 'ESP-VINT-CR',
    nombre: 'Espejos Universales Tipo Vintage (Cromados)',
    clasificacion_abc: 'C',
    stock_inmovilizado: 1,
    ubicacion: 'vitrina de taller',
    capital_congelado_cop: 35000,
    dias_sin_movimiento: 90,
    motivo: 'Solo 1 unidad vendida en 90 días. Riesgo de rayones y deterioro de empaque.',
    sugerencia_accion: 'Mover a mostrador en oferta directa',
    pausado: false
  }
];
